# Generated by Django 3.2.2 on 2021-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210512_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
