# Generated by Django 3.2.2 on 2021-05-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
