# Generated by Django 3.2.2 on 2021-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210512_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
