# Generated by Django 3.2.2 on 2021-05-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_confirmation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
