# Generated by Django 3.2.2 on 2021-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_key', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
