# Generated by Django 3.2.2 on 2021-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210519_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_edit',
            field=models.BooleanField(default=False),
        ),
    ]
