# Generated by Django 3.2.2 on 2021-05-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_allow_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store_location',
            field=models.PositiveSmallIntegerField(default=111),
            preserve_default=False,
        ),
    ]
