# Generated by Django 3.2.2 on 2021-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210519_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_location',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
