# Generated by Django 3.2.2 on 2021-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_store_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSecret',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_key', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Secret',
            new_name='StoreSecret',
        ),
    ]
