# Generated by Django 3.2.3 on 2021-05-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210521_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
