# Generated by Django 3.2.3 on 2021-05-27 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_reportdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdue',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
